### PR TITLE
Convert to CommandBox Module

### PR DESCRIPTION
**Pull request by bdw429s**

### CODE REVIEW

**Comment by bdw429s** [comment]
This requires the bleeding edge of CommandBox (2.3.0).  Type `upgrade --latest` to get it.

**Comment by coldfumonkeh** [comment]
Hey Brad. Modules :) Nice work.

Am getting a Wirebox error when trying to run any of the commands. (I have upgraded to 2.3.0)

```
Error creating command [/commandbox/modules/tweetbox/commands.tweet.validate]

ERROR: Error building: command-/commandbox/modules/tweetbox/commands.tweet.validate -> The parameter wirebox to function init is required but was not passed in.  with constructor arguments: {wirebox={{GETCOLDBOX={getColdbox()}, GETCACHEBOX={getCacheBox()}, AUTOWIRE={autowire(any target, [any mapping, [any targetID, [any annotationCheck]]])}, SETPARENT={setParent(any injector)}, GETBUILDER={getBuilder()}, GETINJECTORID={getInjectorID()}, ISCACHEBOXLINKED={isCacheBoxLinked()}, TYPES={{JAVA={java}, CFC={cfc}, RSS={rss}, WEBSERVICE={webservice}, PROVIDER={provider}, CONSTANT={constant}, FACTORY={factory}, DSL={dsl}}}, BUILDINSTANCE={buildInstance(any mapping, [any initArguments])}, GETSCOPESTORAGE={getScopeStorage()}, GETSCOPEREGISTRATION={getScopeRegistration()}, GETPARENT={getParent()}, GETUTIL={getUtil()}, SHUTDOWN={shutdown()}, GETLOGBOX={getLogBox()}, GETBINDER={getBinder()}, LOCATESCOPEDSELF={locateScopedSelf()}, GETINSTANCE={getInstance([any name, [any dsl, [any initArguments, [any targetObject]]]])}, REGISTERNEWINSTANCE={registerNewInstance(any name, any instancePath)}, CONFIGURE={configure(any binder, any properties)}, REMOVEFROMSCOPE={removeFromScope()}, CONTAINSINSTANCE={containsInstance(any name)}, SCOPES={{REQUEST={request}, PROTOTYPE={NoScope}, NOSCOPE={NoScope}, CACHEBOX={cachebox}, SERVER={server}, APPLICATION={application}, ISVALIDSCOPE={isValidScope([any scope])}, GETVALIDSCOPES={getValidScopes()}, SINGLETON={singleton}, SESSION={session}}}, GETOBJECTPOPULATOR={getObjectPopulator()}, CLEARSINGLETONS={clearSingletons()}, ISCOLDBOXLINKED={isColdBoxLinked()}, GETVERSION={getVersion()}, INIT={init([any binder, [any properties, [any coldbox]]])}, REGISTERDSL={registerDSL(any namespace, any path)}, GETSCOPE={getScope(any scope)}, LOCATEINSTANCE={locateInstance(any name)}, GETSCOPES={getScopes()}, GETEVENTMANAGER={getEventManager()}}}}
Mapping: {INFLUENCECLOSURE={}, METADATA={{INHERITANCETRAIL={[commandbox.modules.tweetbox.commands.tweet.validate, commandbox.modules.tweetbox.commands.tweet.base, commandbox.system.BaseCommand, lucee.Component]}, hint={Validate the settings stored for your Twitter command.
```

**Comment by bdw429s** [comment]
I bet it's related to my move to virtual inheritance (after I tested this command) and the fact that you're calling super.init().  I'll look after church.

**Comment by bdw429s** [comment]
Yep, it's because your `base` class calls super.init().  Due to a behavior in WireBox's virtual inheritance I can't inject things into the base class and have to pass in WireBox via the constructor.  ( https://ortussolutions.atlassian.net/browse/WIREBOX-52 ) 

The easiest fix would be to simply remove the `extends='commandbox.system.BaseCommand'` as that entire bit is optional now.  Then, remove the `super.init()` in your base cfc.

**Pull request merged**
